USE adlister_db;

DROP TABLE IF EXISTS users;


CREATE TABLE users(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(200) NOT NULL,
  email VARCHAR(200) NOT NULL ,
  password VARCHAR(200) NOT NULL,
  PRIMARY KEY (id)
);

